#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"  # repo root, wherever this script is invoked from
ENV_FILE=".env.local"

banner "Portfolio go-live setup"

# ── Stage 1: register a custom domain ──────────────────────────────────────
stage "Custom domain: register"
say "Your JSON-LD/sitemap fallback already points to kaizen.dev (matches the"
say "'Kaizen' easter egg/brand in the Hero), so that's the suggested domain."
say "Pick whichever you actually want to use long-term — it's your call."
open_url "https://dash.cloudflare.com/?to=/:account/registrar/search&domain=kaizen.dev"
step "Search availability and buy the domain (Cloudflare Registrar has no markup;"
step "Namecheap/Google Domains work too if you already have an account there)."
while true; do
  ask DOMAIN "Domain you registered (e.g. kaizen.dev):"
  DOMAIN="${DOMAIN#http://}"
  DOMAIN="${DOMAIN#https://}"
  DOMAIN="${DOMAIN%/}"

  if [[ "$DOMAIN" =~ ^([[:alnum:]]([[:alnum:]-]*[[:alnum:]])?\.)+[[:alpha:]]{2,}(:[[:digit:]]+)?$ ]]; then
    break
  fi

  warn "enter a valid domain only, without a path (e.g. kaizen.dev)"
done
write_env NEXT_PUBLIC_SITE_URL "https://${DOMAIN}"

# ── Stage 2: attach it to the Vercel project ───────────────────────────────
stage "Vercel: attach the domain"
say "Now tell Vercel about the domain so it issues a certificate and routes"
say "traffic to this project."
open_url "https://vercel.com/dashboard"
step "Open the 'portfolio-dev' project → Settings → Domains → Add."
step "Type ${DOMAIN:-your domain} and follow Vercel's on-screen DNS instructions"
step "(it shows the exact A/CNAME records — add them at your registrar's DNS panel)."
note "DNS can take a few minutes to a few hours to propagate. That's normal."
pause "Domain added in Vercel and DNS records saved at the registrar?"

# ── Stage 3: make the app aware of its own real URL ────────────────────────
stage "Vercel: set NEXT_PUBLIC_SITE_URL"
say "The sitemap, hreflang tags, and JSON-LD all read this env var at build"
say "time. Without it in Vercel, production silently falls back to kaizen.dev"
say "even after the domain is live."
open_url "https://vercel.com/dashboard"
step "Open the project → Settings → Environment Variables."
step "Add NEXT_PUBLIC_SITE_URL = https://${DOMAIN:-your-domain} for Production AND Preview."
step "Redeploy (Deployments tab → ⋯ on the latest → Redeploy) so the build picks it up."
pause "Env var added and redeploy triggered?"
note "Also wrote it to ${ENV_FILE} so local npm run build/dev match production."

# ── Stage 4: turn on Vercel Web Analytics ──────────────────────────────────
stage "Vercel: enable Web Analytics"
say "The @vercel/analytics package is already wired into the app layout."
say "It only collects data once Analytics is switched on for this project."
open_url "https://vercel.com/dashboard"
step "Open the project → Analytics tab → Enable Web Analytics (free on Hobby)."
pause "Analytics enabled?"

# ── Stage 5: create a scheduling link ──────────────────────────────────────
stage "Scheduling link (Cal.com)"
say "This powers the optional 'Schedule a call' channel in the Contact section."
say "Leave it blank and skip this stage if you'd rather stick to email/WhatsApp —"
say "the site works fine either way."
open_url "https://cal.com/signup"
step "Create a free account, add one public event type (e.g. '30 min intro call'),"
step "then copy its public booking URL (looks like https://cal.com/yourname/intro)."
ask MEETING_LINK "Paste your booking URL (or leave empty to skip):"

# ── Stage 6: save the scheduling link into the site content ────────────────
stage "Save the scheduling link"
if [[ -n "${MEETING_LINK:-}" ]]; then
  node -e '
    const fs = require("fs");
    const path = "content/portfolio/profile.json";
    const data = JSON.parse(fs.readFileSync(path, "utf8"));
    data.meetingLink = process.argv[1];
    fs.writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
  ' "$MEETING_LINK"
  printf '  %s✓ wrote%s meetingLink → content/portfolio/profile.json\n' "$GREEN" "$RESET"
  note "Commit this change; the Contact section will show the 'Schedule' channel automatically."
else
  note "Skipped — meetingLink left as-is in content/portfolio/profile.json."
fi

finish
note "Next: git add -A && git commit -m 'chore: go live on custom domain' && git push"
